#define PIN_MOSFET_LEFT D5
#define PIN_MOSFET_RIGHT D6
#define PIN_MOSFET_SMELL D7

#define PIN_SEAT_FORWARD D0
#define PIN_SEAT_BACKWARD D8

#define PIN_SEAT_SWITCH_FORWARD D1
#define PIN_SEAT_SWITCH_BACKWARD D2

#define PIN_COMM_RX D3
#define PIN_COMM_TX D4
